compose
HenryMorgan2/working-calendar pull request #1
Opened 2023-09-05 16:06 UTC by HenryMorgan2

2023-09-08 11:44 UTC, epoddubny requested changes

2023-09-08 11:44 UTC, epoddubny commented on docker-compose.yml
> +version: '3.1'
 Давай именовать ветки по номеру issue. Например, feature-${issue-number}

2023-09-08 11:44 UTC, epoddubny commented on docker-compose.yml
> +    image: postgres
В image лучше фиксировать версию, иначе в один момент это может перестать работать.

2023-09-08 11:44 UTC, epoddubny commented on docker-compose.yml
> +  basa:
basa лучше переименовать в db или database

2023-09-08 11:44 UTC, epoddubny commented on docker-compose.yml
> +      POSTGRES_DB: working-calendar
логины и пароли не стоит коммитить в открытые репозитории. Лучше оставить просто название переменных окружения и задавать их на ОС, где запускаешь compose.

2023-09-08 11:44 UTC, epoddubny commented on docker-compose.yml
> +    ports:
добавь volume, иначе при каждом перезапуске база данных и настройки pg-admin будут очищаться.

2023-09-08 11:44 UTC, epoddubny commented on src/main/resources/application.yml
> +      username: working-calendar-rw
Тоже самое, используй переменные окружения для задания логина и пароля

2023-09-09 20:17 UTC, HenryMorgan2 commented on docker-compose.yml
> +    image: postgres
а какую версию зафиксировать? можно написать latest и забыть так скажем?

2023-09-09 20:22 UTC, HenryMorgan2 commented on docker-compose.yml
> +version: '3.1'
типа не branch1, а feature-Запустить Postres и pgadmin-2

2023-09-09 20:22 UTC, HenryMorgan2 commented on docker-compose.yml
> +  basa:
Поправил

2023-09-09 20:43 UTC, HenryMorgan2 commented on docker-compose.yml
> +      POSTGRES_DB: working-calendar
Пробовал вынести в переменные среды и системные переменные перестал собирать докер-кмпоз
Вот так переменные оформлял 
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
 и вот так 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
Не видит переменные

2023-09-09 22:05 UTC, HenryMorgan2 commented on docker-compose.yml
> +    ports:
Добавил. Не знаю как проверить. Посмотрел командой dcoker volume ls
local     working-calendar_pgadmin
local     working-calendar_pgdata

2023-09-09 22:34 UTC, HenryMorgan2 commented on docker-compose.yml
> +    image: postgres
зафиксировал 
postgres:15.4
dpage/pgadmin4:7.6

2023-09-09 22:34 UTC, HenryMorgan2 commented on docker-compose.yml
> +      POSTGRES_DB: working-calendar
Разобрался. надо было комп перезапустить и заработало в  системных переменных

2023-09-09 22:35 UTC, HenryMorgan2 commented on src/main/resources/application.yml
> +      username: working-calendar-rw
сделал

2023-09-11 15:13 UTC, HenryMorgan2 commented on docker-compose.yml
> +version: '3.1'
feature-6 - образец

2023-09-13 21:43 UTC, HenryMorgan2 commented on src/main/resources/application.yml
> +      username: working-calendar-rw
сделал

2023-10-19 08:41 UTC, closed without merging